### ISSUE TITLE
Add loki agent

### ISSUE THREAD

**Issue by dodamih** [ZettaAI/zetta_utils#489] opened 2023-08-16 23:20 UTC
The Grafana integration is sending every log message to the remote server live, resulting in huge overheads when generating SubchunkableApplyFlows. We should add an actual agent running locally to transmit logs to the server in batches.

**Comment by supersergiy** [comment] 2023-08-17 20:16
duplicate of #149

**Closed by supersergiy** 2023-08-17 20:16 UTC
Labels: enhancement
